version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: pastus-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pastus
      MYSQL_ROOT_PASSWORD: my_password  # 추후 수정
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # 처음 뜰 때 테이블 자동 생성
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci